dailyShop/cartOrder/urls.py
from django.urls import path
from . import views

app_name = 'cartOrderApp'

urlpatterns = [
    path('add-to-cart/', views.addToCart, name='addToCart'),    # this need to be in the top
    path('<str:cart_id>/', views.cart, name='cart'),
    path('remove-cart-item/<str:cit_id>/', views.cartItem_remove, name='cartItem_remove'),

    path('create-order/<str:cart_id>/', views.createOrder, name='createOrder'),
    path('order-cancel/<str:order_id>/', views.order_cancel, name='order_cancel'),
    path('order-summary/<str:cart_id>/', views.order_summary, name='order_summary'),

    path('order-placement/cod/<str:order_id>/', views.placeOrder_cod, name='placeOrder_cod'),
    path('order-placement/sslcommerz/<str:order_id>/', views.placeOrder_sslcommerz, name='placeOrder_sslcommerz'),



    # SSLCommerz
    path('sslc/status/', views.sslc_status, name='sslc_status'),
    path('sslc/complete/<str:val_id>/<str:tran_id>/', views.sslc_complete, name='sslc_complete'),
]

dailyShop/dailyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'app_name'), namespace='homeApplication')),
    path('cart/', include(('cartOrder.urls', 'app_name'), namespace='cartOrderApplication')),
    path('auth/', include(('userRegistration.urls', 'app_name'), namespace='userRegApplication')),
]


# Media File URL Configuration (in the development stage)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailyShop/home/urls.py
from django.urls import path
from . import views

app_name = 'homeApp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('product-detail/<str:id>/<str:cart_id>', views.prodDetail, name='prodDetail'),
]

dailyShop/cartOrder/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Product
import random, string


def random_string_generator(size=20, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


class Cart(models.Model):
    cart_id = models.CharField(max_length=100, blank=True)
    total_cart_items = models.PositiveBigIntegerField(default=0)
    is_purchased = models.BooleanField(default=False)
    total_price = models.FloatField(default=0)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.cart_id

    class Meta():
        verbose_name_plural = 'Cart'

    def save(self, *args, **kwargs):
        # If no 'cart_id' isn't passed while creating an order.
        if not len(self.cart_id):
            self.cart_id = str(self.customer) + "_" + random_string_generator()
        super(Cart, self).save(*args, **kwargs)




class CartItem(models.Model):
    cartItem_id = models.CharField(max_length=100, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cartItem_quantity = models.PositiveBigIntegerField(default=0)
    cartItem_price = models.FloatField(default=0)

    class Meta():
        verbose_name_plural = 'Cart Item'

    def save(self, *args, **kwargs):
        # If no 'cart_id' isn't passed while creating an order.
        if not len(self.cartItem_id):
            self.cartItem_id = random_string_generator()

        self.cartItem_price = self.cartItem_quantity * self.product.prod_price

        super(CartItem, self).save(*args, **kwargs)





PAYMENT_CHOICES = [
    ('COD', 'COD'),
    ('SSLCommerz', 'SSLCommerz'),
]
class Order(models.Model):
    order_id = models.CharField(verbose_name='Order ID', max_length=100)
    transaction_id = models.CharField(verbose_name='Transaction ID', max_length=255, blank=True, null=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer+', verbose_name='Customer')
    cart_id = models.ForeignKey(Cart, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    payment_method = models.CharField(verbose_name='Payment Method', max_length=20, choices=PAYMENT_CHOICES, default='COD')
    is_paid = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False)
    delivery_address = models.TextField(verbose_name="Delivery Address", blank=True)
    delivery_time = models.DateField(verbose_name='Delivery Time', auto_now_add=True)

    class Meta:
        verbose_name_plural = "Order"

    def __str__(self) -> str:
        return self.order_id

    def save(self, *args, **kwargs):
        # If no 'order_id' isn't passed while creating an order, then auto-generate the id using randomizer.
        if not len(self.order_id):
            self.order_id = 'order_' + str(self.customer) + "_" + random_string_generator()

        super(Order, self).save(*args, **kwargs)

dailyShop/cartOrder/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import *
from home.models import *
from django.urls.base import reverse

# Payment Gateway Integration
# SSLCommerz
from sslcommerz_python.payment import SSLCSession
from decimal import Decimal
from django.views.decorators.csrf import csrf_exempt



"""
SSLCommerz Implementation Ref:    https://www.youtube.com/watch?v=krTt8Xdchow
"""








"""
Problem:  Item is not added inside the 'cartItem' table
"""





def addToCart(request):
    print('Add to cart function is called!')

    # Construct you logic here
    # ------------
    if request.method == "POST":
        print('Product ID:', request.POST['prod_id'])
        print('Cart ID:', request.POST['cart_id'])
        print('Product Quantity:', request.POST['prod_quantity'])

        cart = Cart.objects.get(cart_id=request.POST['cart_id'])
        product = Product.objects.get(pk=request.POST['prod_id'])
        print('Cart Record (after query):', cart)
        print('Cart Record (after query):', cart.cart_id)
        print('Product Record (after query):', product)


        # make a condition to check if any other same product exist in the cart
        cart_item_duplicate = CartItem.objects.filter(product=product)

        # print('Duplicate CartItem ("Add To Cart" function):', cart_item_duplicate)

        if len(cart_item_duplicate) == 0:
            print('#'*50)
            print('New cart item is created!')
            CartItem.objects.create(
                cart=cart,
                product=product,
                cartItem_quantity=int(request.POST['prod_quantity'])
            )
            print('#'*50)
        else:
            print('#'*50)
            print('Duplicate cart item is found!')
            for cit_dup in cart_item_duplicate:
                cit_dup.cartItem_quantity += int(request.POST['prod_quantity'])
                cit_dup.save()
            print('#'*50)


    # ##########################

    # return redirect('homeApp:homepage')
    # return HttpResponse('Add to cart function is called!')
    return redirect(reverse(
        'cartOrderApp:cart',
        kwargs={'cart_id': cart.cart_id}
    ))



def cart(request, cart_id):
    cart = Cart.objects.get(cart_id=cart_id)
    cartItems = CartItem.objects.filter(cart=cart)

    print('Cart:', cart)
    print('CartItems:', cartItems)


    # for cit in cartItems:
    #     print(cit)



    return HttpResponse('Customer Cart page is called!')

    context = {
        'title': 'Cart',
        'cart': cart,
        'cart_id': cart_id,
        'cartItems': cartItems,
    }
    return render(request, 'cartOrder/cart.html', context)
    pass



def cartItem_remove(request, cit_id):
    print('CartItem remove is called!')

    print('Cart Item ID:', cit_id)
    #
    cartItem_record = CartItem.objects.get(cartItem_id=cit_id)
    # print('Cart Item ID (after query):', cartItem_record.cartItem_id)
    print('Cart ID (after "CartItem" query):', cartItem_record.cart.cart_id)

    cartItem_record.delete()

    cart_record = Cart.objects.get(cart_id=cartItem_record.cart.cart_id)
    # print('Cart ID (after "Cart" query):', cart_record.cart_id)

    # return HttpResponse({
    #     'msg': 'Cart remove function is called!',
    #     'CartItem_ID': cit_id,
    # })
    # return redirect("")
    return redirect(reverse(
        'cartOrderApp:cart',
        kwargs={'cart_id': cart_record.cart_id}
    ))
    pass






def createOrder(request, cart_id):
    if request.method == 'POST':
        # print('Cart ID:', cart_id)

        cart = Cart.objects.get(cart_id=cart_id)
        # print('Cart (order function):', cart)
        cartItems = CartItem.objects.filter(cart=cart)

        for cit in cartItems:
            print('cart item (order function):', cit)

        cust = User.objects.get(username=request.user)
        # print('customer (order function):', cust)


        # Check if any order of "not-cancelled" & "not-paid" exists
        order = Order.objects.filter(customer=cust, cart_id=cart, is_paid=False, is_cancelled=False)

        # print('createOrder function --- Order:', order)
        if len(order) == 0:
            # create the order
            # print('Create Order function -- A new order is created! Then it will be redirected to the order_summary page!')
            Order.objects.create(
                customer=cust,
                cart_id=cart,
                price=cart.total_price,
            )
        else:
            # update the order regarding the cart
            # print('Create Order function -- The order record is updated! Then it will be redirected to the order_summary page!')
            # order_total_price = 0
            for o in order:
                # print('Create Order function -- Order ID:', o.order_id)
                # print('Create Order function -- Cart Price:', o.cart_id.total_price)
                o.price = o.cart_id.total_price
                o.save()

    return redirect(reverse(
        'cartOrderApp:order_summary',
        kwargs={'cart_id': cart_id}
    ))




def order_summary(request, cart_id):
    print('#'*50)
    print('Order Summary function is called! Cart ID:', cart_id)

    cart = Cart.objects.get(cart_id=cart_id)
    # print('Cart (order Summary function):', cart)
    cartItems = CartItem.objects.filter(cart=cart)
    # print('Cart Items (order Summary function):', cartItems)
    cust = User.objects.get(username=request.user)
    order = Order.objects.get(customer=cust, cart_id=cart, is_paid=False, is_cancelled=False)
    print('Order:', order)
    print('#' * 50)

    context = {
        'title': 'Order Page',
        'cart_id': cart_id,
        'cartItems': cartItems,
        'order': order,
    }
    return render(request, 'cartOrder/order.html', context)
    pass





def order_cancel(request, order_id):
    print('order_cancel function -- order id:', order_id)
    order = Order.objects.get(order_id=order_id)
    print('order_cancel function -- order (after query):', order)
    order.is_cancelled = True
    order.save()
    return redirect('homeApp:homepage')
    # return HttpResponse('The order is cancelled!')




def placeOrder_cod(request, order_id):
    if request.method == "POST":
        print('Order is placed! (COD). Order ID:', order_id)
        order = Order.objects.get(order_id=order_id)
        order.payment_method = 'COD'
        order.is_paid = True
        order.save()
        return HttpResponse('Order is placed! (COD)')





def placeOrder_sslcommerz(request, order_id):
    if request.method == "POST":
        print('Order is placed! (SSLCommerz). Order ID:', order_id)
        order = Order.objects.get(order_id=order_id, is_paid=False, is_cancelled=False)
        # order.payment_method = 'SSLCommerz'
        # order.save()

        print('Order Total Price ("placeOrder_sslcommerz" func):', order.price)
        print('Order Total Item Quantity ("placeOrder_sslcommerz" func):', order.cart_id.total_cart_items)

        order_price = order.price
        order_quantity = order.cart_id.total_cart_items

        store_id = 'creat621675119a224'
        store_pass = 'creat621675119a224@ssl'

        mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=store_id,
                                sslc_store_pass=store_pass)

        status_url = request.build_absolute_uri(reverse('cartOrderApp:sslc_status'))
        mypayment.set_urls(success_url=status_url, fail_url=status_url,
                           cancel_url=status_url, ipn_url=status_url)

        mypayment.set_product_integration(total_amount=Decimal(order_price), currency='BDT', product_category='None',
                                          product_name='demo-product', num_of_item=order_quantity,
                                          shipping_method='YES', product_profile='None')
        customer = request.user
        print('Customer name:', customer.username)

        # for d in dir(customer):
        #     print( d )

        mypayment.set_customer_info(name=customer.username, email=customer.email, address1='demo address',
                                    address2='demo address 2', city='Dhaka', postcode='1207', country='Bangladesh',
                                    phone='01711111111')
        mypayment.set_shipping_info(shipping_to='demo customer', address='demo address', city='Dhaka', postcode='1209',
                                    country='Bangladesh')
        response_data = mypayment.init_payment()

        print('#'*50)
        print('Response Data:', response_data)
        print('#'*50)
        return redirect(response_data['GatewayPageURL'])
    #     return redirect('cartOrderApp:sslc_status')
    # return HttpResponse('Order is placed! (SSLCommerz)')





@csrf_exempt
def sslc_status(request):
    if request.method == 'post' or request.method == 'POST':
        payment_data = request.POST
        print('='*50)
        print('sslc_status method:',payment_data)

        print('sslc_status method (status):', payment_data['status'])
        status = payment_data['status']
        if status == 'VALID':
            tran_id = payment_data['tran_id']
            val_id = payment_data['val_id']

            return redirect(reverse(
                'cartOrderApp:sslc_complete',
                kwargs={'val_id': val_id, 'tran_id': tran_id}
            ))

        print('='*50)
        return render(request, 'sslcommerz/status.html')
    pass


def sslc_complete(request, val_id, tran_id):
    order = Order.objects.filter(customer=request.user, is_paid=False, is_cancelled=False).first()
    print('sslc_complete method ("Order" query):', order)

    # modify the 'Order' record
    order.is_paid = True
    order.payment_method = 'SSLCommerz'
    order.order_id = val_id
    order.transaction_id = tran_id
    order.save()

    # modify the 'Cart' record
    cart = Cart.objects.get(cart_id=order.cart_id.cart_id, is_purchased=False)
    cart.is_purchased = True

dailyShop/templates/cartOrder/cart.html
<!doctype html>
{% include 'base.html' %}

{% block title %}

    <title> {{ title }} </title>

{% endblock %}



{% block content %}

    <h1>Cart</h1>

<!--    <table class="table">-->
<!--        <thead>-->
<!--            <tr>-->
<!--                <th scope="col">#</th>-->
<!--                <th scope="col">Cart Item ID</th>-->
<!--                <th scope="col">Cart</th>-->
<!--                <th scope="col">Product</th>-->
<!--                <th scope="col">Cart Item Quantity</th>-->
<!--                <th scope="col">Cart Item Price</th>-->
<!--            </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--            {% for cit in cartItems %}-->
<!--            <tr>-->
<!--                <th scope="row">{{ forloop.counter }}</th>-->
<!--                <td>{{ cit.cartItem_id }}</td>-->
<!--                <td>{{ cit.cart }}</td>-->
<!--                <td>{{ cit.product }}</td>-->
<!--                <td>{{ cit.cartItem_quantity }}</td>-->
<!--                <td>{{ cit.cartItem_price }}</td>-->
<!--            </tr>-->
<!--            {% endfor %}-->
<!--        </tbody>-->
<!--    </table>-->







    <div class="container-fluid">
        <div class="row">
            <div class="col-3 bg-secondary">asd</div>
            <div class="col-6 bg-danger">

                <h3> Cart ID: {{ cart_id }} </h3>

                <table class="table">
                    <tbody>
                        {% for cit in cartItems %}
                        <tr>
                            <td class="container">
                                <div class="row">
                                    <div class="col">
                                        <img src="{{ cit.product.prod_image.url }}" alt="prod-img" style="width:10rem; height:10rem">
                                    </div>
                                    <div class="col"> <b>{{ cit.product.prod_name }}</b>
                                        {{ cit.cartItem_id }}
                                    </div>
                                    <div class="col"> <b>{{ cit.product.prod_price }}</b> </div>
                                    <div class="col"> <b>{{ cit.cartItem_quantity }}</b>
                                        <a href="{% url 'cartOrderApplication:cartItem_remove' cit.cartItem_id %}" style="text-decoration:none; color:black;">
                                            <i class="bi bi-trash3-fill" style="font-size: 2rem;"></i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


            </div>
            <div class="col bg-info">
                <h3>Cart Subtotal</h3>

                Price: <b> {{ cart.total_price }} </b>

                <br><br><br>

                <form action="{% url 'cartOrderApp:createOrder' cart_id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-success">Proceed to Checkout</button>
                </form>
            </div>
        </div>
    </div>




{% endblock %}

dailyShop/templates/cartOrder/order.html
<!doctype html>
{% include 'base.html' %}

{% block title %}

    <title> {{ title }} </title>

{% endblock %}



{% block content %}

    <h1>Order Page</h1>

    <h3>Order ID: {{ order.order_id }} </h3>


    <div class="container-fluid">
        <div class="row">
            <div class="col-3 bg-secondary">asd</div>
            <div class="col-6 bg-danger">

                <table class="table">
                    <tbody>
                        {% for cit in cartItems %}
                        <tr>
                            <td class="container">
                                <div class="row">
                                    <div class="col">
                                        <img src="{{ cit.product.prod_image.url }}" alt="prod-img" style="width:10rem; height:10rem">
                                    </div>
                                    <div class="col"> <b>{{ cit.product.prod_name }}</b>
                                        {{ cit.cartItem_id }}
                                    </div>
                                    <div class="col"> <b>{{ cit.product.prod_price }}</b> </div>
                                    <div class="col"> <b>{{ cit.cartItem_quantity }}</b> </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


            </div>
            <div class="col bg-info">
                <h3>Select a payment method</h3>

                <h4> Order Price: {{ order.price }} </h4>

                <div class="row">
                    <div class="col">
                        <a href="{% url 'cartOrderApp:order_cancel' order.order_id %}"
                            class="btn btn-danger"> <b>Cancel Order</b> </a>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col">
                        <form action="{% url 'cartOrderApp:placeOrder_cod' order.order_id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="cod" value="COD">
                            <button type="submit" class="btn btn-md btn-dark"> <b>COD</b> </button>
                        </form>
                    </div>
                    <div class="col">
                        <form action="{% url 'cartOrderApp:placeOrder_sslcommerz' order.order_id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="cod" value="SSLCommerz">
                            <button type="submit" class="btn btn-md btn-dark"> <b>SSLCommerz</b> </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}