dailyShop/cartOrder/urls.py
from django.urls import path
from . import views

app_name = 'cartOrderApp'

urlpatterns = [
    path('add-to-cart/', views.addToCart, name='addToCart'),    # this need to be in the top
    path('<str:cart_id>/', views.cart, name='cart'),
    path('remove-cart-item/<str:cit_id>/', views.cartItem_remove, name='cartItem_remove'),

    path('create-order/<str:cart_id>/', views.createOrder, name='createOrder'),
    path('order-cancel/<str:order_id>/', views.order_cancel, name='order_cancel'),
    path('order-summary/<str:cart_id>/', views.order_summary, name='order_summary'),

    path('order-placement/cod/<str:order_id>/', views.placeOrder_cod, name='placeOrder_cod'),
    path('order-placement/sslcommerz/<str:order_id>/', views.placeOrder_sslcommerz, name='placeOrder_sslcommerz'),



    # SSLCommerz
    path('sslc/status/', views.sslc_status, name='sslc_status'),
    path('sslc/complete/<str:val_id>/<str:tran_id>/', views.sslc_complete, name='sslc_complete'),
]

dailyShop/dailyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'app_name'), namespace='homeApplication')),
    path('cart/', include(('cartOrder.urls', 'app_name'), namespace='cartOrderApplication')),
    path('auth/', include(('userRegistration.urls', 'app_name'), namespace='userRegApplication')),
]


# Media File URL Configuration (in the development stage)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dailyShop/home/urls.py
from django.urls import path
from . import views

app_name = 'homeApp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('product-detail/<str:id>/<str:cart_id>', views.prodDetail, name='prodDetail'),
]

dailyShop/userRegistration/urls.py
from django.urls import path
from . import views


app_name = 'userRegApp'



urlpatterns = [
    path('user-registration/', views.registration, name='registration'),
    path('user-sign-in/', views.signin, name='signin'),
    path('user-sign-out/', views.user_logout, name='logout'),
]

dailyShop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %} {% endblock %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>

    <h1 class="text-danger">
        Cart ID: {{ cart_id }}
        <br>
        Cart Page: <a href="{% url 'cartOrderApplication:cart' cart_id %}" class="btn btn-lg btn-warning">Cart</a>
        <br>
        Logged in as: {{ user }}
    </h1>

    <h1>
        <a href="{% url 'homeApp:homepage' %}">Home</a>
    </h1>

    <a href="{% url 'userRegApp:registration' %}" class="btn btn-lg btn-primary">Register</a>
    <a href="{% url 'userRegApp:signin' %}" class="btn btn-lg btn-primary">Login</a>
    <a href="{% url 'userRegApp:logout' %}" class="btn btn-lg btn-danger">Logout</a>

    {% block content %} {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>