topMart/cartOrder/urls.py
from django.urls import path
from . import views

app_name = 'cartOrderApp'

urlpatterns = [
    path('addtocart/', views.addToCart, name='addCart'),
]

topMart/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='homeApp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('productdetail/<str:id>', views.prodDetails, name='prodDetails'),
]

topMart/topMart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'app_name'), namespace='homeApplication')),
    path('', include(('cartOrder.urls', 'app_name'), namespace='cartOrderApp')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topMart/cartOrder/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Product
import random, string


def random_id_generator(size=20, chars= string.ascii_lowercase + string.digits):
	return ''.join(random.choice(chars) for _ in range(size))



# Create your models here.

class Cart(models.Model):
	cart_id = models.CharField(max_length = 200, blank = True)
	total_cart_items = models.PositiveBigIntegerField(default = 0)
	total_price = models.FloatField(default = 0)
	customer = models.ForeignKey(User, on_delete = models.CASCADE)

	class Meta():
		verbose_name_plural = 'Cart'		

	def save(self, *args, **kwargs):
		self.cart_id = str(self.customer) + '_' + random_id_generator()
		super(Cart,self).save(*args, **kwargs)


class CartItem(models.Model):
	cartItem_id = models.CharField(max_length = 200, blank = True)
	cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
	product = models.ForeignKey(Product, on_delete = models.CASCADE)
	cartItem_quantity = models.PositiveBigIntegerField(default = 0)
	cartItem_price = models.FloatField(default = 0)

	class Meta():
		verbose_name_plural = 'Cart Items'

	def save(self, *args, **kwargs):
		if not len(self.cartItem_id):
			self.cartItem_id =  random_id_generator()

		print('price', self.product.prod_price)

		# update price
		self.cartItem_price = self.cartItem_quantity * self.product.prod_price
		super(CartItem,self).save(*args, **kwargs)



# class Data(models.Model):
# 	cartItem_id = models.CharField(max_length = 200, blank = True)
# 	cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
# 	product = models.ForeignKey(Product, on_delete = models.CASCADE)
# 	cartItem_quantity = models.PositiveBigIntegerField(default = 0)
# 	cartItem_price = models.FloatField(default = 0)


# 	class Meta():
# 		verbose_name_plural = 'Data'

topMart/home/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
	prod_name = models.CharField(max_length = 150)
	prod_desc = models.TextField()
	prod_img_url = models.TextField()
	prod_price = models.FloatField(default=0.00)

	prod_img = models.ImageField(upload_to = 'prodImage', default = 'prodImage/default_img.png', blank=True)

	# for specify name in backend
	class Meta():
		verbose_name_plural = 'Products'

topMart/cartOrder/views.py
from django.shortcuts import render, redirect
from .models import *
from home.models import *


# Create your views here.
def addToCart(request):
    print('d to cart hitted.')

    if request.method == "POST":
    	print("prod Id: ", request.POST['prod_id'])
    	# print("prod Id: ", request.POST['prod_des'])
    	# print("card Id: ", request.POST['cart_id'])
    	# print("prod quantity: ", request.POST['prod_quantity'])


    	# cart = Cart.objects.get(cart_id = request.POST['cart_id'])
    	product = product.objects.get(pk=request.POST['prod_id'])

    	# print('CCart', cart)
    	print('Prod', product)

    return redirect('homeApp:homepage')
    
    # 	cart = Cart.objects.get(cart_id=request.POST[cart_id])

topMart/home/views.py
from django.shortcuts import render
from .models import *
from cartOrder.models import *

# Create your views here.


def homepage(request):
	product = Product.objects.all()

	context = {
		'product' : product
	}

	return render(request, 'home/homepage.html', context)


def prodDetails(request, id):
	prod = Product.objects.get(pk=id)
	cart = Cart.objects.all()
	print(cart)
	context = {
	'prod' : prod,
	'cart':cart
	}

	return render(request, 'home/productDetail.html', context)
	pass

topMart/templates/home/data.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>My</title>
<!-- <title>{% block title %}{% endblock %}</title> -->
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% if not is_popup and is_nav_sidebar_enabled %}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/nav_sidebar.css" %}">
  <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
{% endif %}
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    {% block header %}
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% translate 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% translate 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endblock %}
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    <div class="main" id="main">
      {% if not is_popup and is_nav_sidebar_enabled %}
        {% block nav-sidebar %}
          {% include "admin/nav_sidebar.html" %}
        {% endblock %}
      {% endif %}
      <div class="content">
        {% block messages %}
          {% if messages %}
            <ul class="messagelist">{% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
            {% endfor %}</ul>
          {% endif %}
        {% endblock messages %}
        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
          {% block pretitle %}{% endblock %}
          {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
          {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock %}
          {% block content %}
            {% block object-tools %}{% endblock %}
            {{ content }}
          {% endblock %}
          {% block sidebar %}{% endblock %}
          <br class="clear">
        </div>
        <!-- END Content -->
        {% block footer %}<div id="footer"></div>{% endblock %}
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

topMart/templates/home/homepage.html
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">



	<title>TopMart</title>
</head>

<body>

	<!-- 	<main>
		
	</main>
-->
	<!-- header start-->


	<header>
		<div class="container bg-light">
			<nav class="navbar navbar-expand-lg navbar-light">
				<a class="navbar-brand" href="#">Top Mart</a>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav m-auto">
						<li class="nav-item active">
							<a class="nav-link" href="#">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">All Products</a>
						</li>
					</ul>
					
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>

				</div>

			</nav>
		</div>


		<section>
			<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					<div class="carousel-item active">
						<img class="d-block w-100"
							src="https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
							alt="First slide">
					</div>
					<div class="carousel-item">
						<img class="d-block w-100"
							src="https://images.unsplash.com/photo-1610395219791-21b0353e43cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
							alt="Second slide">
					</div>
					<div class="carousel-item">
						<img class="d-block w-100"
							src="https://images.unsplash.com/photo-1612817159623-0399784fd0ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80"
							alt="Third slide">
					</div>
				</div>
				<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</section>

	</header>
	<!-- header end-->



	<!-- main section start-->

	<main>

		<!-- products -->
		<div class="container">
			<div class="row">

				{% for prod in product %}
				<div class="col-lg-3 col-md-4 col-sm-6 my-3">
					<div class="card">
						<img src='{{ prod.prod_img.url }}' class="card-img-top" alt="Product image"
							style="width: 100%; height: 300px">
						<div class="card-body">
							<h5 class="card-title">{{prod.prod_name |truncatechars:20}}</h5>
							<h6 class="card-title text-primary">${{prod.prod_price}}</h6>
							<p class="card-text">{{prod.prod_desc | truncatechars:40}}</p>
							<a href="{% url 'homeApplication:prodDetails' prod.id %}" class="btn btn-success">Buy
								Now</a>
							<!-- <p>{{ prod.id }}</p> -->
						</div>
					</div>
				</div>
				{% endfor %}

			</div>
		</div>
	</main>
	<!-- main section end-->

	<!-- footer start -->
	<footer>

	</footer>

	<!-- footer end -->










	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
		crossorigin="anonymous"></script>


</body>

</html>

topMart/templates/home/productDetail.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">



	<title>TopMart</title>
</head>
<body>

<!-- 	<main>
		
	</main>
-->
<!-- header start-->


<header>
	<!-- <div class="container"> -->
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">Navbar</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Link</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Dropdown
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</li>
					<li class="nav-item">
						<a class="nav-link disabled" href="#">Disabled</a>
					</li>
				</ul>
				<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
				<!-- </div> -->
			</nav>
			<section>
				<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img class="d-block w-100" src="https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" alt="First slide">
						</div>
						<div class="carousel-item">
							<img class="d-block w-100" src="https://images.unsplash.com/photo-1610395219791-21b0353e43cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80" alt="Second slide">
						</div>
						<div class="carousel-item">
							<img class="d-block w-100" src="https://images.unsplash.com/photo-1612817159623-0399784fd0ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80" alt="Third slide">
						</div>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</section>
		</div>

	</header>
	<!-- header end-->



	<!-- main section start-->

	<main>
		<!-- products -->
		<div class="container my-5">
			<div class="row">
				<div class="col-lg-6 col-xs-12 col-sm-6">
					<img src="{{prod.prod_img.url}}" class="img-fluid"/>
				</div>
				<div class="col-lg-6 col-xs-12 col-sm-6">
					<div class="prod_details">
						<h3>{{prod.prod_name}}</h3>
						<!-- <h3>IDdd:{{prod.prod_img_url}}</h3> -->
						<h4 class="text-red">Price: {{prod.prod_price}}</h4>
						<p>{{prod.prod_desc}}</p>
						<form action="{% url 'cartOrderApp:addCart' %}" method="POST">
							{% csrf_token %}
							<!-- <div class="form-group">
								<label for="exampleInputEmail1"></label>
								<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="prixe">
							</div> -->
							<!-- <p>Ida: {{ cart.cart_id }}</p>
							<p>Ida: {{ prod.prod_name }}</p> -->

							<!-- <div class="form-group">
								<label for="exampleInputPassword1">Quantity</label>
								<input type="number" class="form-control" id="prod_quantity" min="1" max="10" required name="card.card_id"> 
							</div> -->
							<div class="form-group">
								<!-- <label for="exampleInputPassword1">Quantity</label> -->
								<input type="hidden" class="form-control"  id="prod_id" name ="prod_id" value={{ prod.pk }}> 
							</div>
							<div class="form-group">
								<label for="exampleInputPassword1">Quantity</label>
								<input type="number" class="form-control" id="prod_quantity" min="1" max="10" required name="card_id"> 
							</div>
							<button type="submit" class="btn btn-primary my-3">Add to cart</button>
						</form>
					</div>
				</div>
			</div>
		</div>

		<!-- form -->
		<div class="container">
			<div class="row">
				
			</div>
		</div>

	</main>
	<!-- main section end-->


	<!-- footer start -->
	<footer>

	</footer>

	<!-- footer end -->










	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</body>
</html>